language: java
dist: xenial
sudo: required
install:
  - TERM=dumb ./gradlew -q assemble
matrix:
  include:
    - name: postgresql 9.6
      jdk: openjdk11
      env: PROFILE="-Dspring.profiles.active=travis -Ddbenv=PGSQL-TRAVIS -Dpgsql9.6"
      addons:
        postgresql: "9.6"
    - name: postgresql 10
      jdk: openjdk11
      env: PROFILE="-Dspring.profiles.active=travis -Ddbenv=PGSQL-TRAVIS -Dpgsql10"
      addons:
        postgresql: "10"

before_script:
  - psql -c 'create database alfio;' -U postgres
script:
  - TERM=dumb ./gradlew build jacocoTestReport $PROFILE
  - sonar-scanner
after_success:
  ./gradlew coveralls
addons:
    sonarcloud:
        organization: "alfio-event"
        token:
            secure: "NP89kR383hQ1Cd/ynzruiGo3n17FUlOyCQCNQrrCQPTe7HNAMqht66fR10SyoZzUype4pBbyLIEUqC4hs89ZQRaRFtTPQWgk0KNQpax/wkf1zi8wusrWYBuyiCoN5riibAlu8qav7OKTpv8P3OP/Zt1KgvKabmcy6S5tOi0VV4s="
