name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                postgresql: ['9.6','10','11','12']
        services:
            postgres:
                image: postgres:${{ matrix.postgresql }}
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: alfio
                ports:
                    - 5432:5432
                # needed because the postgres container does not provide a healthcheck
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v1
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
                  restore-keys: |
                      ${{ runner.os }}-gradlew-
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
              id: extract_branch
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Build with Gradle
              run: ./gradlew build distribution jacocoTestReport -Dspring.profiles.active=travis -Ddbenv=PGSQL-TRAVIS -Dpgsql${{ matrix.postgresql }}
            - name: upload-to-coveralls
              if: matrix.postgresql == '12' # run only once
              run: ./gradlew coveralls
              env:
                 COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
            -   name: Configure Docker
                if: ${{ github.repository == 'alfio-event/alf.io' && matrix.postgresql == '12'}}
                uses: docker/setup-buildx-action@v1
            -   name: Login to Container Registry
                if: ${{ github.repository == 'alfio-event/alf.io' && matrix.postgresql == '12'}}
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ secrets.CR_USER }}
                    password: ${{ secrets.CR_PAT }}
            -   name: Push Docker image
                if: ${{ github.repository == 'alfio-event/alf.io' && matrix.postgresql == '12'}}
                uses: docker/build-push-action@v2
                with:
                    context: ./build/dockerize
                    tags: |
                        ghcr.io/alfio-event/alf.io:${{ steps.extract_branch.outputs.branch }}
                    push: true